config/routes.rb
Rails.application.routes.draw do
 
  namespace :site do
    get 'welcome/index'
  end
  namespace :usuarios_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
    resources :admins
    resources :subjects
    resources :questions
  end
  devise_for :admins
  devise_for :usuarios
  
  get 'home', to: 'site/welcome#index'

  root to: 'site/welcome#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # kaminari
  paginates_per 5
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject
  has_many :answers
  accepts_nested_attributes_for :answers
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  # aqui está herdando tanto a autenticação quanto o layout específico.
  before_action :set_admin, only: [:edit, :update, :destroy]

  def index
    @admins = Admin.all.order(:id).page(params[:page])
  end

  def new
    @admin = Admin.new 
  end

  def create 
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: "Successfully Created"
    else 
      render :new
    end
  end

  def edit 
  end

  def update
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
    params_admin
    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_path, notice: "Successfully Updated"
    else 
      render :edit
    end
  end

  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: "Administrador excluído com sucesso!"
    else
      render :index
    end
  end

  private
  
  def params_admin
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :get_subjects, only: [:new, :edit]

  def index
    @questions = Question.includes(:subject)
                         .order(:id)
                         .page(params[:page])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params_question)
    if  @question.save
      redirect_to admins_backoffice_questions_path, notice: "Questão cadastrada com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update    
    if  @question.update(params_question)
      redirect_to admins_backoffice_questions_path, notice: "Questão atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if  @question.destroy
      redirect_to admins_backoffice_questions_path, notice: "Questão excluída com sucesso!"
    else
      render :index
    end
  end

  private
  
  def params_question
    params.require(:question).permit(:description, :subject_id,
       answers_attributes: [:id, :description, :correct, :_destroy])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def get_subjects
    @subjects = Subject.all
  end
end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
  before_action :set_subject, only: [:edit, :update, :destroy]

  # def index
  #   respond_to do |format|
  #     format.html { @subjects = Subject.all.order(:description).page(params[:page]) }
  #     format.pdf  { @subjects = Subject.all.order(:description) }
  #     format.json { @subjects = Subject.all.order(:description) }
  #   end
  # end

  def index
    @subjects = Subject.all.order(:description).page(params[:page])
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(params_subject)
    if  @subject.save
      redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área cadastrado com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update    
    if  @subject.update(params_subject)
      redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if @subject.destroy
      redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área excluído com sucesso!"
    else
      render :index
    end
  end

  private
  
  def params_subject
    params.require(:subject).permit(:description)
  end

  def set_subject
    @subject = Subject.find(params[:id])
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
end

app/controllers/usuarios_backoffice/welcome_controller.rb
class UsuariosBackoffice::WelcomeController < ApplicationController
  def index
  end
end

app/controllers/usuarios_backoffice_controller.rb
class UsuariosBackofficeController < ApplicationController
  before_action :authenticate_usuario!
  layout 'usuarios_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/usuarios_backoffice/welcome_helper.rb
module UsuariosBackoffice::WelcomeHelper
end

app/helpers/usuarios_backoffice_helper.rb
module UsuariosBackofficeHelper
end

app/views/admins_backoffice/questions/edit.html.erb
<h1>EDITANDO QUESTÕES</h1>
<%#= @admin.inspect %>

  <% if @question.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            
            <ul>
              <% @question.errors.full_messages.each do |message| %>
                <li> <%= message %> </li>
              <% end %>
            </ul>
        </div>
  <% end %>

<%= form_with(model: [ :admins_backoffice, @question ], local: true) do |form| %>
                        
  <div class="form-group">
      <%= form.label :description %>
      <%= form.text_field :description, 
                class:"form-control", 
              placeholder: 'Questão'  %>
  </div>

  <div class="form-group">
  <%= form.label :subject_id %>
  <%= form.collection_select(:subject_id, @subjects, :id, :description) %>
  </div>

  <button type="submit" class="btn btn-default">
    <%= 'button.save' %>
  </button>
<% end %>

app/views/admins_backoffice/questions/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><%= t('message.listing', model: @questions.model_name.human(count: 2)) %></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
      <thead>
          <tr>
              <th>#</th>
              <th>Questões</th>
              <th>Assuntos/Áreas</th>
              <th>
                <p><%= link_to 'New Question', new_admins_backoffice_question_path %></p>
                  <i class="fa fa-plus"></i>
              </th>
          </tr>
      </thead>
      <tbody>
          <% @questions.each do |question| %>
          <tr>
              <td><%= question.id %></td>
              <td><%= sanitize question.description.truncate(110) %></td>
              <td><%= question.subject.description.truncate(50) %></td>
              <td style="width: 100px">

                  <%= link_to "Edit", edit_admins_backoffice_question_path(question.id) %>
                  <i class="fa fa-edit"></i>

                <%= button_to "Delete", admins_backoffice_question_path(question.id), method: :delete, data: { confirm: 'Are you sure ?' } %>
                  <i class="fa fa-minus"></i>

              </td>
          </tr>
          <% end %>
      </tbody>
  </table>

  <div class="text-center">
    <%= paginate @questions %>
  </div>
</div>

app/views/admins_backoffice/questions/new.html.erb
<h1>NOVA QUESTÃO</h1>
<%#= @admin.inspect %>

  <% if @question.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            
            <ul>
              <% @question.errors.full_messages.each do |message| %>
                <li> <%= message %> </li>
              <% end %>
            </ul>
        </div>
  <% end %>

<%= form_with(model: [ :admins_backoffice, @question ], local: true) do |form| %>
                        
  <div class="form-group">
      <%= form.label :description %>
      <%= form.text_field :description, 
                class:"form-control", 
              placeholder: 'placeholder.question_description'  %>
  </div>

    <div class="form-group">
      <%= form.label :subject %>
      <%= form.collection_select(:subject_id, @subjects, :id, :description) %>
  </div>

  <button type="submit" class="btn btn-default">
    <%= 'button.save' %>
  </button>
<% end %>

app/views/admins_backoffice/subjects/edit.html.erb
<h1>EDITANDO ASSUNTOS/ÁREAS</h1>
<%#= @admin.inspect %>

  <% if @subject.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            
            <ul>
              <% @subject.errors.full_messages.each do |message| %>
                <li> <%= message %> </li>
              <% end %>
            </ul>
        </div>
  <% end %>

<%= form_with(model: [ :admins_backoffice, @subject ], local: true) do |form| %>
                        
  <div class="form-group">
      <%= form.label :description %>
      <%= form.text_field :description, 
                class:"form-control", 
              placeholder: 'Descrição do assunto/área'  %>
  </div>

  <button type="submit" class="btn btn-default">
    <%= 'button.save' %>
  </button>
<% end %>

app/views/admins_backoffice/subjects/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Listing All Subjects</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
      <thead>
          <tr>
              <th>#</th>
              <th><%#= translate_attribute(@subjects, :description) %></th>
              <th>
                <%= link_to new_admins_backoffice_subject_path, class:"btn btn-success btn-circle" do %>
                  <i class="fa fa-plus"></i>
                <% end %>
                <%= link_to admins_backoffice_subjects_path(format: :pdf), class:"btn btn-danger btn-circle" do %>
                  <i class="fa fa-file-pdf-o"></i>
                <% end %>
              </th>
          </tr>
      </thead>
      <p><%= link_to 'New Subject', new_admins_backoffice_subject_path %></p>
      <tbody>
          <% @subjects.each do |subject| %>
          <tr>
              <td><%= subject.id %></td>
              <td><%= subject.description %></td>
              <td style="width: 100px">
                <%= link_to "Edit", edit_admins_backoffice_subject_path(subject.id) %>
                <%#= link_to edit_admins_backoffice_subject_path(subject), class:"btn btn-primary btn-circle" do %>
                  <i class="fa fa-edit"></i>
                <%# end %>
                
                <%= button_to "Delete", admins_backoffice_subject_path(subject.id), method: :delete, data: { confirm: 'Are you sure ?' } %>
                
              </td>
          </tr>
          <% end %>
      </tbody>
  </table>

  <div class="text-center">
    <%= paginate @subjects %>
  </div>
</div>

app/views/admins_backoffice/subjects/new.html.erb
<h1>NOVO ASSUNTO/ÁREA</h1>
<%#= @admin.inspect %>

  <% if @subject.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            
            <ul>
              <% @subject.errors.full_messages.each do |message| %>
                <li> <%= message %> </li>
              <% end %>
            </ul>
        </div>
  <% end %>

<%= form_with(model: [ :admins_backoffice, @subject ], local: true) do |form| %>
                        
  <div class="form-group">
      <%= form.label :description %>
      <%= form.text_field :description, 
                class:"form-control", 
              placeholder: 'placeholder.admin_description'  %>
  </div>

  <button type="submit" class="btn btn-default">
    <%= 'button.save' %>
  </button>
<% end %>

app/views/admins_backoffice/welcome/index.html.erb
<h1>AdminsBackoffice::Welcome#index</h1>
<p>Find me in app/views/admins_backoffice/welcome/index.html.erb</p>
<p>
<%= button_to "Fazer Log_off [Administrador]", destroy_admin_session_path, method: :delete %>
</p>

app/views/site/welcome/index.html.erb
<h1>Site::Welcome#index</h1>
<p>Find me in app/views/site/welcome/index.html.erb</p>

<% if usuario_signed_in? && current_usuario.present? %>
  <p>Usuário ESTÁ logado / <%= current_usuario.email %></p>
<% else %>
  <p>Usuário NÃO está logado / </p>
<% end %>

<% if admin_signed_in? && current_admin.present? %>
  <p>Administrador ESTÁ logado / <%= current_admin.email %></p>
<% else %>
  <p>Administrador NÃO está logado / </p>
<% end %>

<%= link_to "Administrators", admins_backoffice_welcome_index_path %>

app/views/usuarios_backoffice/welcome/index.html.erb
<h1>UsuariosBackoffice::Welcome#index</h1>
<p>Find me in app/views/usuarios_backoffice/welcome/index.html.erb</p>
<p>
<%= button_to "Fazer Log_off [Usuário]", destroy_usuario_session_path, method: :delete %>
</p>